EnterpriseAssignment/EnterpriseAssignment/Controllers/AuthorController.cs
using EnterpriseAssignment.DataModel;
using EnterpriseAssignment.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EnterpriseAssignment.Controllers
{
    public class AuthorController : Controller
    {
        Entities Entity = new Entities();
        // GET: Author

        [Authorize]
        [Route("Author/Index/{username}")]
        public ActionResult Index(string username)
        {
            AuthorAndBlogListModel model = new AuthorAndBlogListModel();

            IEnumerable<Blog> enumBlogs = Entity.Blogs.Where(x => x.AspNetUser.UserName == username).OrderByDescending(x => x.DateCreated).AsEnumerable();
            List<Blog> blogs = enumBlogs.ToList();
            ViewData["username"] = username;

            AspNetUser user = Entity.AspNetUsers.Where(x => x.UserName == username).SingleOrDefault();

            model.Blogs = blogs;
            model.User = user;

            return View(model);
        }
        
        [Authorize]
        public ActionResult MyProfile()
        {
            string currentUsername = User.Identity.GetUserName();
            AspNetUser currentUser = Entity.AspNetUsers.Where(x => x.UserName == currentUsername).SingleOrDefault();

            return View(currentUser);
        }
    }
}

EnterpriseAssignment/EnterpriseAssignment/Controllers/BlogController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dropbox.Api;
using System.Threading.Tasks;
using Dropbox.Api.Users;
using System.IO;
using System.Text;
using Dropbox.Api.Files;
using Dropbox.Api.Sharing;
using EnterpriseAssignment.DataModel;
using EnterpriseAssignment.Models;
using System.Data.Entity.Validation;

namespace EnterpriseAssignment.Controllers
{
    public class BlogController : Controller
    {
        Entities Entity = new Entities();
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            List<Category> categories = Entity.Categories.ToList();

            BlogCreateModel model = new BlogCreateModel();
            model.Categories = GetSelectListItems(categories);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Create(BlogCreateModel blog, HttpPostedFileBase Image)
        {
            List<Category> categories = Entity.Categories.ToList();
            blog.Categories = GetSelectListItems(categories);

            try
            {
                if (ModelState.IsValid)
                {
                    if(Image.ContentLength <= 150000000)
                    {
                        DropboxClient dbx = new DropboxClient("9Svq7UQdvCAAAAAAAAAAH7YMzry4Hg8aOuIJ5agh81BxXaJ-Szn_BvpEYz18UhIc");

                        MemoryStream target = new MemoryStream
                        {
                            Position = 0
                        };
                        Image.InputStream.CopyTo(target); // generates problem in this line
                        target.Position = 0;

                        string currentUser = User.Identity.Name;

                        string imageId = Guid.NewGuid().ToString();

                        FileMetadata updated = await dbx.Files.UploadAsync("/" + currentUser + "/" + imageId,
                        WriteMode.Overwrite.Instance,
                        body: target);

                        SharedLinkMetadata sharedLink = await dbx.Sharing.CreateSharedLinkWithSettingsAsync("/" + currentUser + "/" + imageId);

                        Blog b = new Blog() { BlogId = Guid.NewGuid(), Heading = blog.Heading, Content = blog.Content, Category_Fk = blog.Category_Fk, Username_Fk = User.Identity.GetUserId(), DateCreated = DateTime.Now, Image = sharedLink.Url.Replace("dl=0", "raw=1"), Tags = blog.Tags, Categories = GetSelectListItems(categories) }; 

                        Entity.Blogs.Add(b);
                        Entity.SaveChanges();

                        TempData["Message"] = "Successfully created!";

                        return View(blog);
                    }

                    TempData["Error"] = "File size must be smaller than 150MB!";
                    return View(blog);
                }

                else
                {
                    TempData["Error"] = "Please fill in all details.";
                    return View(blog);
                }
            }

            catch(DbEntityValidationException ex)
            {
                TempData["Error"] = "Something went wrong. We are working to fix this.";
                return View(blog);
            }
        }
        
        [Authorize]
        public ActionResult Edit(Guid id)
        {
            try
            {
                Blog blogDetails = Entity.Blogs.Where(x => x.BlogId == id).SingleOrDefault();

                if(blogDetails.AspNetUser.UserName == User.Identity.Name)
                    return View(blogDetails);

                TempData["Error"] = "This blog does not belong to you!";
                return View();
            }

            catch
            {
                return View();
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Blog model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Username_Fk == User.Identity.GetUserId())
                    {
                        Blog oldDetails = Entity.Blogs.Where(x => x.BlogId == model.BlogId).SingleOrDefault();

                        oldDetails.Heading = model.Heading;
                        oldDetails.Content = model.Content;
                        oldDetails.Tags = model.Tags;

                        Entity.SaveChanges();

                        TempData["Message"] = "Successfully edited!";

                        return RedirectToAction("Index", "Home");
                    }

                    TempData["Error"] = "This blog does not belong to you!";
                    return RedirectToAction("Index", "Home");
                }

                TempData["Error"] = "Please fill all fields!";
                return View();
            }

            catch
            {
                TempData["Error"] = "Something went wrong with the edit. Make sure you insert the correct information";
                return View(model);
            }
        }

        [Authorize]
        public ActionResult Delete(Guid id)
        {
            try
            {
                Blog toDelete = Entity.Blogs.Where(x => x.BlogId == id).SingleOrDefault();
                if (User.Identity.Name == toDelete.AspNetUser.UserName)
                {

                    Entity.Blogs.Remove(toDelete);
                    Entity.SaveChanges();

                    TempData["Message"] = "Successfully deleted!";

                    return RedirectToAction("Index", "Home");
                }

                TempData["Error"] = "Something went wrong. Try again later.";
                return RedirectToAction("Index", "Home");
            }

            catch
            {
                TempData["Error"] = "Something went wrong with the delete. This Blog might not exist anymore!";
                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize]
        public ActionResult BlogDetails(string id)
        {
            try
            {
                Guid blogId = new Guid(id);
                Blog blog = Entity.Blogs.Where(x => x.BlogId == blogId).SingleOrDefault();

                return View(blog);
            }

            catch
            {
                TempData["Error"] = "Blog-id format was incorrect.";
                return View();
            }
        }

        private IEnumerable<SelectListItem> GetSelectListItems(IEnumerable<Category> elements)
        {
            var selectList = new List<SelectListItem>();
            
            foreach (var element in elements)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.CategoryId.ToString(),
                    Text = element.CategoryName
                });
            }

            return selectList;
        }
    }
}

EnterpriseAssignment/EnterpriseAssignment/Controllers/CategoryController.cs
using EnterpriseAssignment.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EnterpriseAssignment.Controllers
{
    public class CategoryController : Controller
    {
        Entities Entity = new Entities();
        // GET: Category

        [Authorize]
        [Route("Category/Index/{categoryName}")]
        public ActionResult Index(string categoryName)
        {
            if (categoryName == "MvcDotNet")
                categoryName = "Mvc.Net";

            IEnumerable<Blog> enumBlogs = Entity.Blogs.Where(x => x.Category.CategoryName == categoryName).OrderByDescending(x => x.DateCreated).AsEnumerable();
            List<Blog> blogs = enumBlogs.ToList();
            ViewData["categoryName"] = categoryName;

            return View("Index", "", blogs);
        }
    }
}

EnterpriseAssignment/EnterpriseAssignment/Views/Blog/BlogDetails.cshtml
@model EnterpriseAssignment.DataModel.Blog

<p class="text-success">@TempData["Message"]</p>
<p class="text-danger">@TempData["Error"]</p>

<div class="row">
    <div class="container panel panel-warning col-md-10 col-md-offset-1">
        <div class="row">
            <div class="panel panel-heading">
                <h3>@Model.Heading</h3>
            </div>
            <div class="panel panel-body">
                @{ ViewData["category"] = Model.Category.CategoryName;}
                <p>Category: @Html.ActionLink(Model.Category.CategoryName, "Index", "Category", new { categoryName = (string)ViewData["category"] }, null)</p>
                <p>Created By: @Html.ActionLink(Model.AspNetUser.UserName, "Index", "Author", new { username = Model.AspNetUser.UserName} , null)</p>
                <img src="@Model.Image" width="100%" height="100%" />
                <p>Content: @Model.Content</p>
                <p>Tags: @Model.Tags</p>
            </div>
            @if (Model.AspNetUser.UserName == User.Identity.Name)
            {
                <div class="panel panel-footer">
                    @Html.ActionLink("Edit", "Edit", new { id = Model.BlogId }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Delete", "Delete", new { id = Model.BlogId }, new { @class = "btn btn-danger" })
                </div>
            }
        </div>
    </div>
</div>

EnterpriseAssignment/EnterpriseAssignment/Views/Blog/Create.cshtml
@model EnterpriseAssignment.Models.BlogCreateModel

@{
    ViewBag.Title = "Create";
}

<h2>@ViewBag.Title</h2>
<h2 class="text-success">@TempData["Message"]</h2>
<h2 class="text-danger">@TempData["Error"]</h2>

@using (Html.BeginForm( "Create", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Heading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
           <div class="col-md-10">
                <input name="Image" type="file" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_Fk, Model.Categories, null, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnterpriseAssignment/EnterpriseAssignment/Views/Blog/Edit.cshtml
@model EnterpriseAssignment.DataModel.Blog

@{
    ViewBag.Title = "Edit Blog";
}

<h2>Edit Blog</h2>

<h2 class="text-success">@TempData["Message"]</h2>
<h2 class="text-danger">@TempData["Error"]</h2>

<div class="row col-md-12">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.BlogId)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Username_Fk)

            <div class="form-group">
                @Html.LabelFor(model => model.Heading, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Heading, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Heading, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>